### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden for url: https://connect.garmin.com/proxy/workout-service/workouts?start=0&limit=100

### ISSUE THREAD

**Issue by AGlandier** [mkuthan/garmin-workouts#77]
Hello,
When i'm trying to use your work to send workouts on my garmin account, i'm getting this error :
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://connect.garmin.com/proxy/workout-service/workouts?start=0&limit=100
I suppose that this is garmin website which is denying me the access,
Do I need an API key for their Workouts API or the issue may be caused by something else ?
(I'm using a Python 3.11.6 virtual environment with the last releases of the requirements)
Thx for your help

**Comment by jmsmkn** [comment]
I was facing the same problem. This library includes its [own Garmin SSO auth](https://github.com/mkuthan/garmin-workouts/blob/main/garminworkouts/garmin/session.py). I couldn't work out how to fix it so switched the authentication out for [Garth](https://pypi.org/project/garth/) and updated the endpoints I used in `garminclient.py`, ending up with something like:

```python
import garth

...

garth.login(username, password)

...

class GarminClient:
    
    ...

    def update_workout(self, workout_id, workout):
        path = f"{GarminClient._WORKOUT_SERVICE_ENDPOINT}/workout/{workout_id}"

        response = garth.client.request(
            "PUT",
            "connectapi",
            path,
            api=True,
            json=workout,
        )
        response.raise_for_status()
```

Maybe this will help you solve the same issue for the list view.

**Comment by AGlandier** [comment]
Thanks for your help ! This solution worked, the error evolved into a 402 error, which has been raised in another issue ;) I am at least moving forward !
