### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by darkzbaron** [mkuthan/garmin-workouts#9]
Hi there, any plan for scheduling existing workouts?

**Comment by mkuthan** [comment]
Hi @darkzbaron, unfortunatelly I do not use Garmin workouts anymore. My shitty trainer (Direto) reports different numbers than my power meters so I have to use 3rd party apps with power match feature (like TrainerDay or BreakAway).

But feel free to enhance the tool if you have some spare time, I'll we be glad to help you.

**Comment by darkzbaron** [comment]
Hi there, sorry to hear that! Ok anyway I'll try to get it done by tomorrow but it will probably be quick and dirty. The plan is to add a new workflow for scheduling a training number previously obtained via the -list argument, I have sniffed the request, it is a PUT but I need to figure out how the JSON payload work! I'll play with that and let you know!

**Comment by mkuthan** [comment]
Merged into master
